export const members: Record<string, string> = {
    '0': "Asaph Almeida",
    '1': "André Queiroz",
    '2': "Ara(mys/mito/boy) Matos",
    '3': "Ana Sofia",
    '4': "SaFabão Filho",
    '5': "Marcus Maninho",
    '6': "Miguel Jesus do Sul",
    '7': "Pedro Intruso 1 Campos",
    '8': "Rafael Ferrari",
    '9': "Raphael Carvalho",
    '10': "Vinicius Castro",
    '11': "Will",
    '12': "Talita Vieira",
    '12': "Intruso 1",
    '13': "Intruso 2",
    '14': "Duplamente Intruso",
} ;
