export const members: Record<string, string> = {
    '0': "Asaph Almeida",
    '1': "André Queiroz",
    '2': "Ara(mys/mito/boy) Matos",
    '3': "Ana Sofia",
    '4': "SaFabão Filho",
    '5': "Marcus Maninho",
    '6': "Miguel Jesus do Sul",
    '7': "Pedro Intruso 1 Campos",
    '8': "Rafael Ferrari",
    '9': "Raphael Carvalho",
    '10': "Vinicius Castro",
    '11': "Will",
    '12': "Talita Vieira",
    '13': "Don Diego de la Vega",
    '14': "Intruso 1",
    '15': "Duplamente Intruso",
    '16': "Duplamente e um cadinho a mais Intruso",
} ;
